### ISSUE TITLE
Home page is not updated when template changes

### ISSUE THREAD

**Issue by fccoelho** [wq/wq.app#118]
The rendered `index.html` is not updated after I make changes to the template, even though I run deploy.sh 0.0.2 to update the templates.
This only happens when run via wsgi (I am running it in a docker container). 
On the development server everything works as it should (but it's useless to me since I need it to work in production)
The funny thing is that the source obtained from the GET request on / is the updated one, but the page rendered is the older v. 0.0.1. 
I initially thought it might be a browser cache issue, but it persists even after clearing the cache, and even on different browsers. 
I have rulled out caching of the docker image, because it presists even after I deleted all images and rebuild the containers from scratch.

I have also tried deleting htdocs and letting the deploy.sh script rebuild it. Nothing seems to work.
I have tried deleting myapp.appcache from both within `/app` and `/htdocs`

It seems clear that some caching is going on to make this error possible, But I cant figure out where or how to fix it! 

Any suggestions?

**Comment by fccoelho** [comment]
I think that detailed documentation of how the pages are rendered would be a great contribution to debug issues like this one. On vanilla Django apps we know how views are generated and rendered so that we can have a clear and deterministic development cycle. Wq dropped Django views and templates and in exchange offers a page rendering mechanism that is at the same time obscure and unreliable.

**Comment by sheppard** [comment]
As you may have seen in #111 and other tickets, wq is replacing the old page rendering system with React and Material UI.  Among the top reasons for the change is to improve reliability as well as the developer experience.  I agree that better documentation would have helped debug the old system, but the main goal for now is to document the new renderer and release 1.3.

The decision to forgo Django views was because a core feature of wq is the ability to operate entirely offline and then sync to Django later.  I could see eventually implementing a online-only version of wq that does use Django views, but that is not in the roadmap for now.

**Comment by sheppard** [comment]
I just released [wq.app 1.3 beta](https://github.com/wq/wq.app/releases/tag/v1.3.0b1) and completely overhauled the [documentation site](https://wq.io/).  The new rendering system has been working well in production settings, so I recommend using it for all new projects.
