### ISSUE TITLE
Watching for template changes in react environment

### ISSUE THREAD

**Issue by simonwinter** [wq/wq.app#120]
Is there a recommended approach to watching for template changes in the react version of the app?

Currently the templates are inlined via the `update_json.sh` script. I'm running my dev environment inside a docker container & have taken to useing `inotify-tools` to detect template changes & update the templates.json file as necessary.

This seems like a bit of a clunky approach - is there a better way to watch for changes in dev? Or am I doing something wrong here?

**Comment by sheppard** [comment]
There isn't currently a built-in way to handle this, so suggestions are helpful.   To be clear, the templates are only needed for the Mustache/jQuery Mobile renderer.  In the upcoming React/Material UI implementation, templates.json is not used at all, since the UI is generated directly from the config.json and registered React components.  That said, it will still be useful to regenerate config.json whenever the Django models change.

**Comment by sheppard** [comment]
I updated wq.db to automatically regenerate data/config.js whenever `runserver` reloads - see [this commit](https://github.com/wq/wq.db/commit/bc8412abe6110d1e5142fca74810e40db047cce7).  I didn't implement the same logic for data/templates.js (which is deprecated), but you could use a similar approach.  Basically you would just need to specify a custom [Django AppConfig](https://docs.djangoproject.com/en/3.1/ref/applications/) and make sure it calls the appropriate shell commands in [`ready()`](https://docs.djangoproject.com/en/3.1/ref/applications/#django.apps.AppConfig.ready).
