### ISSUE TITLE
Choose layer icon depending on submitted data

### ISSUE THREAD

**Issue by MartinPontius** [wq/wq.app#129]
Hi,

I would like to choose my layer icon depending on what data was actually submitted. 
I use wq 1.1.0 with Python 3.6.9.

According to the documentation (https://v1.wq.io/1.1/docs/map-js), I can use a function to choose between icons that have been registered before via map.createIcon():

> The name of an icon to use, or a template that will compile to an icon name, or a function returning an icon name. If a template or a function, it will be called with the feature.properties for each feature in the dataset. Icon names should first be registered via map.createIcon() (see below).

However, when I use a function I get the following error:

```
...
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'function' is not JSON serializable
```

The respective code snippets are these:

```
in main.js:

map.createIcon("icon_name", {'iconUrl': "/images/icon.png"), 'iconSize': [30, 30]});

in my_model/rest.py:

def choose_icon(feature_properties):
    # add some filter depending on feature_properties
    return "icon_name"

rest.router.register_model(
    My_model,
    fields="__all__",
    map=[{
        'mode': 'list',
        'layers': [{
            'type': 'geojson',
             ...
            'icon' : choose_icon,
        }],
    }, {
   ...
```

Any ideas what could be the problem?

**Comment by sheppard** [comment]
The 1.1 docs are assuming you would somehow modify the [configuration object](https://wq.io/config) with a JavaScript wrapper to inject a JavaScript icon generation function.  In retrospect this was not a good design, since it causes the configuration object to become a mix of server-generated JSON and client code.  A better solution (that more closely matches what you are trying to do) would be to register a custom serializer:

```python
# my_model/serializers.py:
from rest_framework import serializers
from wq.db.rest.serializers import ModelSerializer
from .models import My_model


class MyModelSerializer(ModelSerializer):
    icon = serializers.SerializerMethodField()
    def get_icon(self, instance):
        # add some filter depending on instance properties
        return "icon_name"

   class Meta:
        model = My_model
        fields = '__all__'

# my_model/rest.py:
from .serializers import MyModelSerializer


rest.router.register_model(
    My_model,
    serializer=MyModelSerializer,
    map=[{
        'mode': 'list',
        'layers': [{
            'type': 'geojson',
             ...
            'icon' : '{{icon}}',
        }],
    }, {
   ...
```

FWIW, wq 1.3 and later do a better job of separating configuration from code.  In 1.3, the general solution is to register an custom [overlay type](https://wq.io/overlays/) through a [JavaScript plugin](https://wq.io/plugins/), and then the config just needs to specify the type name to use it.

**Comment by MartinPontius** [comment]
@sheppard Thank you for your explanation. I have already implemented a workaround using a mustache template expression with a bunch of boolean variables added to the context. It is doing the job, but definitely not the best way to implement it. In the future, I will consider the method(s) you have suggested.
