### ISSUE TITLE
Deployment script (deploy.sh) fails to optimize ES6 code

### ISSUE THREAD

**Issue by tomaszn** [wq/wq.app#83]
I use ES6 template strings in my project. Now when using `optimize: uglify` in the project's `app/wq.yml`, the deployment script fails:
```sh
Tracing dependencies for: myproject
Uglify file: /home/me/myproject/htdocs-build/js/myproject.js
Error: Cannot uglify file: /home/me/myproject/htdocs-build/js/myproject.js. Skipping it. Error is:
SyntaxError: Unexpected character '`' (line: 51393, col: 50, pos: 1706728)
```
It fails also on destructuring assignments.

Including Babel in the process of building would make the script compressable even when using new JS features. It would also become runnable on older platforms and browsers.

Another option, just for enabling the optimization, would be to use experimental branch of the optimizer: https://github.com/mishoo/UglifyJS2#harmony. Require.js 2.3.3 already supports partially ES6 with upgraded Esprima, and there is a possibility to use Harmony: https://github.com/requirejs/r.js/issues/942.

**Comment by sheppard** [comment]
For wq 1.0, I would be open to incorporating the experimental harmony-compatible Uglify.  It should ideally "just work" by following the steps in requirejs/r.js#942 and replacing build/r.js with the output.

Babel and broader ES6 support would mean a number of other considerations that I'd like to put off until after the 1.0 release: see #84.

**Comment by tomaszn** [comment]
The latest r.js release incorporated Esprima 4: requirejs/r.js#963.

**Comment by sheppard** [comment]
Thanks, I plan to incorporate the latest r.js as part of #92.  I am also going to see if it might be easy to run babel in the same way.  (As it turns out, one of PyMiniRacer's default examples is using babel.)

**Comment by sheppard** [comment]
Hmm, so r.js 2.3.4 includes Esprima 4 but not [uglify-es@3](https://www.npmjs.com/package/uglify-es), which would be needed to optimize ES6.  Per requirejs/r.js#959, the issue is that the Uglify 3 API (for both ES6 and ES5) is different than the Uglify 2 API.  The official recommendation for now is to set `"optimize": "none"` and then use a separate minifier for ES6 code.  So, to get this working we will either need to:

 * Create a custom r.js for python-requirejs, using the last tag from the harmony branch that is still compatible with Uglify 2 API (probably [harmony-v2.8.22](https://github.com/mishoo/UglifyJS2/releases/tag/harmony-v2.8.22))
 * Or, bundle a copy of uglify-es with python-requirejs or in a separate python package, and come up with a custom API for triggering it (e.g., perhaps `"optimize": "uglify-es"` would be popped out of the config before sending the files to r.js)
 * Or, incorporate Babel as a mandatory preprocessing step for ES6 users (either as part of python-requirejs or a separate package).

The last option probably makes the most sense, with the caveat that it assumes you always want ES5 code at the end (which might not be the case if you are only targeting the latest browsers).

**Comment by tomaszn** [comment]
In case of the last option, we could drop Uglify and use (beta) babel/minify. According to their benchmark, it works good enough, although minifying takes much more time: https://github.com/babel/minify#benchmarks

**Comment by sheppard** [comment]
Yes, I agree that babel/minify seems like the way to go in the long term.  For now, I incorporated [babeljs-python](https://github.com/yetone/babeljs-python) for a simple `wq babel` command (without minifying).  babeljs-python is currently bundling an older standalone version of babel (`babel-browser`) but it shouldn't be too hard to upgrade to the latest `babel-standalone` at some point.

However, there is currently no published `babel-minify-standalone`, so I'm waiting on that before suggesting it as a plugin for babeljs-python.  (There is an older build called babeli-standalone but I'd rather start from the latest version).

I'll be keeping an eye on this ticket:
https://github.com/babel/minify/issues/671

**Comment by sheppard** [comment]
Now that wq supports full integration with npm, we can use babel-minify directly instead of trying to package it for PyPI.   In fact, I think it makes sense to simplify the non-npm use case to not require a build at all.  See the release notes for [wq.app 1.3 alpha](https://github.com/wq/wq.app/releases/tag/v1.3.0a1#user-content-es-modules) for more details.
