### ISSUE TITLE
Sending application version with each request

### ISSUE THREAD

**Issue by tomaszn** [wq/wq.app#91]
I'd like to attach the version number to each request to make sure users use the latest version of the application.
Is it accessible on the client side?
What would be the best place to add this functionality (I consider adding it as an additional HTTP request header)?

**Comment by sheppard** [comment]
Since network traffic is routed through jQuery's AJAX functions, you could try using [$.ajaxSetup](https://api.jquery.com/jquery.ajaxsetup/) to set the header.  The version should always be available from the `"data/version"` module.

Perhaps something like this?
```javascript
define(['jquery', 'data/version'], function($, version) {
    $.ajaxSetup({
        "headers": {
            "X-App-Version": version
        }
    });
});
```

I haven't tested it but that should be pretty close.

**Comment by tomaszn** [comment]
Works perfectly, thank you!
I added the `data/version` module to the `main.js` and put the `ajaxSetup` snippet there.
